/**********************************************************************************************
 Code generated by TrierDSL Plug-in
 WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
 ***********************************************************************************************/

package br.com.billing.domain.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum ImportStatus {

    AWAITING_PROCESSING("Aguardando processamento"),
    PROCESSING("Processando"),
    IMPORTED("Importado"),
    ERROR("Erro"),
    CANCELED("Cancelado");

    private final String label;
}

